version: "3.8"

services:
  backend:
    container_name: itml-backend
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - itml-network

  mongo:
    container_name: itml-mongo
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: itml
    volumes:
      - mongo-data:/data/db
    networks:
      - itml-network

networks:
  itml-network:
    driver: bridge

volumes:
  mongo-data:
